"""Automated report generation for antenna designs."""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional
from jinja2 import Template


class ReportGenerator:
    """
    Generates comprehensive design reports in various formats.

    Supports:
    - PDF reports (via LaTeX or HTML to PDF)
    - HTML reports
    - Markdown reports
    """

    def __init__(self, output_dir: str = "reports"):
        """
        Initialize report generator.

        Args:
            output_dir: Directory for saving reports
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_design_report(
        self,
        design_data: Dict[str, Any],
        format: str = "markdown"
    ) -> str:
        """
        Generate comprehensive design report.

        Args:
            design_data: Design package with all results
            format: Output format ('markdown', 'html')

        Returns:
            Path to generated report
        """
        if format == "markdown":
            return self._generate_markdown_report(design_data)
        elif format == "html":
            return self._generate_html_report(design_data)
        else:
            raise ValueError(f"Unsupported format: {format}")

    def _generate_markdown_report(self, design_data: Dict[str, Any]) -> str:
        """Generate Markdown report."""

        template = Template("""
# Antenna Design Report

**Workflow ID**: {{ workflow_id }}
**Generated**: {{ timestamp }}
**Duration**: {{ duration_seconds | round(1) }} seconds
**Iterations**: {{ iterations }}

---

## Executive Summary

The autonomous multi-agent system has completed the antenna design process.

### Termination Condition
- **Status**: {{ termination_condition }}
- **Reason**: {{ termination_reason }}

---

## Mission Requirements

### Frequency Specification
- **Center Frequency**: {{ requirements.frequency.center_frequency_ghz }} GHz
- **Bandwidth**: {{ requirements.frequency.bandwidth_mhz or 'Not specified' }} MHz

### Performance Requirements
- **Target Gain**: {{ requirements.radiation_pattern.gain_dbi }} dBi
- **Beamwidth (Az)**: {{ requirements.radiation_pattern.beamwidth_azimuth_deg or 'Not specified' }}°
- **Beamwidth (El)**: {{ requirements.radiation_pattern.beamwidth_elevation_deg or 'Not specified' }}°
- **Sidelobe Level**: {{ requirements.radiation_pattern.sidelobe_level_db }} dB
- **Polarization**: {{ requirements.polarization.value }}

### Physical Constraints
- **Max Mass**: {{ requirements.physical.max_mass_kg or 'Not specified' }} kg
- **Dimensions**: {{ requirements.physical.max_length_m or 'N/A' }} ×
  {{ requirements.physical.max_width_m or 'N/A' }} ×
  {{ requirements.physical.max_height_m or 'N/A' }} m

---

## Final Design

### Architecture
{{ final_design.architecture | default('Not available', true) }}

### Geometry
{{ final_design.geometry | default('Not available', true) }}

### Materials
{{ final_design.materials | default('Not available', true) }}

---

## Performance Results

### Simulation Results
{{ final_design.simulation_results | default('Not available', true) }}

### Validation Results
{{ final_design.validation_results | default('Not available', true) }}

---

## Design Iteration History

{% for perf in performance_history[:5] %}
### Iteration {{ perf.iteration }}
- **Timestamp**: {{ perf.timestamp }}
- **Performance**: {{ perf.performance }}
{% endfor %}

{% if performance_history | length > 5 %}
*... and {{ performance_history | length - 5 }} more iterations*
{% endif %}

---

## Communication Statistics

- **Total Messages**: {{ communication_stats.total_messages }}
- **Active Agents**: {{ communication_stats.active_agents }}
- **Active Conversations**: {{ communication_stats.active_conversations }}

### Messages by Type
{% for msg_type, count in communication_stats.messages_by_type.items() %}
- **{{ msg_type }}**: {{ count }}
{% endfor %}

---

## Conclusion

The design process completed successfully with {{ iterations }} optimization iterations.
All requirements have been analyzed and the final design has been validated.

**Next Steps**:
1. Detailed electromagnetic simulation validation
2. Prototype fabrication and testing
3. Integration with spacecraft platform

---

*Generated by Astraeus Apertura Multi-Agent Antenna Design System*
""")

        content = template.render(
            workflow_id=design_data.get("workflow_id", "N/A"),
            timestamp=datetime.now().isoformat(),
            duration_seconds=design_data.get("duration_seconds", 0),
            iterations=design_data.get("iterations", 0),
            termination_condition=design_data.get("termination_condition", "N/A"),
            termination_reason=design_data.get("termination_reason", "N/A"),
            requirements=design_data.get("requirements", {}),
            final_design=design_data.get("final_design", {}),
            design_history=design_data.get("design_history", []),
            performance_history=design_data.get("performance_history", []),
            communication_stats=design_data.get("communication_stats", {}),
        )

        # Save report
        report_path = self.output_dir / f"design_report_{design_data.get('workflow_id', 'unknown')}.md"
        report_path.write_text(content)

        return str(report_path)

    def _generate_html_report(self, design_data: Dict[str, Any]) -> str:
        """Generate HTML report."""

        template = Template("""
<!DOCTYPE html>
<html>
<head>
    <title>Antenna Design Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
        h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
        h2 { color: #34495e; border-bottom: 1px solid #bdc3c7; padding-bottom: 5px; margin-top: 30px; }
        h3 { color: #7f8c8d; }
        table { border-collapse: collapse; width: 100%; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        th { background-color: #3498db; color: white; }
        .summary-box { background-color: #ecf0f1; padding: 20px; border-radius: 5px; margin: 20px 0; }
        .metric { display: inline-block; margin: 10px 20px; }
        .metric-label { font-weight: bold; color: #7f8c8d; }
        .metric-value { font-size: 1.2em; color: #2c3e50; }
    </style>
</head>
<body>
    <h1>Antenna Design Report</h1>

    <div class="summary-box">
        <div class="metric">
            <span class="metric-label">Workflow ID:</span>
            <span class="metric-value">{{ workflow_id }}</span>
        </div>
        <div class="metric">
            <span class="metric-label">Duration:</span>
            <span class="metric-value">{{ duration_seconds | round(1) }}s</span>
        </div>
        <div class="metric">
            <span class="metric-label">Iterations:</span>
            <span class="metric-value">{{ iterations }}</span>
        </div>
    </div>

    <h2>Mission Requirements</h2>
    <table>
        <tr>
            <th>Parameter</th>
            <th>Value</th>
        </tr>
        <tr>
            <td>Center Frequency</td>
            <td>{{ requirements.frequency.center_frequency_ghz }} GHz</td>
        </tr>
        <tr>
            <td>Target Gain</td>
            <td>{{ requirements.radiation_pattern.gain_dbi }} dBi</td>
        </tr>
        <tr>
            <td>Polarization</td>
            <td>{{ requirements.polarization.value }}</td>
        </tr>
    </table>

    <h2>Performance Summary</h2>
    <p><strong>Status:</strong> {{ termination_condition }}</p>
    <p><strong>Reason:</strong> {{ termination_reason }}</p>

    <h2>Communication Statistics</h2>
    <p>Total Messages: {{ communication_stats.total_messages }}</p>
    <p>Active Agents: {{ communication_stats.active_agents }}</p>

    <hr>
    <p><em>Generated by Astraeus Apertura on {{ timestamp }}</em></p>
</body>
</html>
""")

        content = template.render(
            workflow_id=design_data.get("workflow_id", "N/A"),
            timestamp=datetime.now().isoformat(),
            duration_seconds=design_data.get("duration_seconds", 0),
            iterations=design_data.get("iterations", 0),
            termination_condition=design_data.get("termination_condition", "N/A"),
            termination_reason=design_data.get("termination_reason", "N/A"),
            requirements=design_data.get("requirements", {}),
            communication_stats=design_data.get("communication_stats", {}),
        )

        # Save report
        report_path = self.output_dir / f"design_report_{design_data.get('workflow_id', 'unknown')}.html"
        report_path.write_text(content)

        return str(report_path)

    def generate_comparison_report(
        self,
        ai_design: Dict[str, Any],
        baseline_design: Dict[str, Any],
        format: str = "markdown"
    ) -> str:
        """
        Generate comparison report between AI and baseline designs.

        Args:
            ai_design: AI-generated design data
            baseline_design: Baseline design data
            format: Output format

        Returns:
            Path to generated report
        """
        # Simplified comparison report
        template = Template("""
# Design Comparison Report

## AI Design vs. Baseline Design

### Performance Comparison

| Metric | AI Design | Baseline | Improvement |
|--------|-----------|----------|-------------|
| Gain (dBi) | {{ ai_gain }} | {{ baseline_gain }} | {{ (ai_gain - baseline_gain) | round(2) }} |
| Mass (kg) | {{ ai_mass }} | {{ baseline_mass }} | {{ (baseline_mass - ai_mass) | round(2) }} |

---

*Generated on {{ timestamp }}*
""")

        content = template.render(
            ai_gain=ai_design.get("gain", 0),
            baseline_gain=baseline_design.get("gain", 0),
            ai_mass=ai_design.get("mass", 0),
            baseline_mass=baseline_design.get("mass", 0),
            timestamp=datetime.now().isoformat(),
        )

        report_path = self.output_dir / "comparison_report.md"
        report_path.write_text(content)

        return str(report_path)
